### ISSUE TITLE
<head></head> Tag'i

### ISSUE THREAD

**Issue by RaviHamidov** [rftglyv/PragmatechFoundationProject#4]
https://github.com/rftglyv/PragmatechFoundationProject/blob/cccb3bb9d3743c01dd5b0b7f2b5761523afa4f67/FirstHTMLTry/index.html#L10

Burada <head></head> tag'i arasina hansi tip informasiyalara olduqu barede bir [Menbe](https://www.yazilimkodlama.com/html/html-head-kullanimi/) paylasiram faydali ola biler.

**Comment by rftglyv** [comment]
Təşəkkürlər
