### ISSUE TITLE
Tag'larin yanlis istifadesi

### ISSUE THREAD

**Issue by RaviHamidov** [rftglyv/PragmatechFoundationProject#7]
https://github.com/rftglyv/PragmatechFoundationProject/blob/cccb3bb9d3743c01dd5b0b7f2b5761523afa4f67/FirstHTMLTry/index.html#L27

Her hansi yeni bir tag'den istifade ederken nece istifade olunduqu barede arasdirma aparsaniz daha yaxsi ola biler, [Bu Menbe](https://www.w3schools.com/TAgs/default.asp) faydali ola biler.

**Comment by rftglyv** [comment]
<a>'nı nəzərdə tutursunuzsa o bookmark üçündü.
